---
:authentication:
  :method: OAuth2

  # Auth parameters for OAuth2.0 method.
  # Set the OAuth2 client id and secret. Register your application here to
  # obtain these values:
  #   https://code.google.com/apis/console#access
#  :oauth2_client_id: 1023867723478-focl6ai09bplusuoo7hd99g1sru18323.apps.googleusercontent.com
#  :oauth2_client_secret: RHffitvb1E_6KPL9zVakSIfA
  :oauth2_client_id: 1023867723478-uck0o77dbg4nlqg3capbnhb8qn127nbf.apps.googleusercontent.com
  :oauth2_client_secret: KiUhwvWe5qhYcvs5Si9me3-q
  # Optional, see: https://developers.google.com/accounts/docs/OAuth2WebServer
  #:oauth2_state: INSERT_OAUTH2_STATE_HERE
  #:oauth2_access_type: offline
  #:oauth2_approval_prompt: INSERT_OAUTH2_APPROVAL_PROMPT_HERE
  # Callback is set up by the application at runtime.
  #:oauth2_callback: INSERT_OAUTH2_CALLBACK_URL_HERE

  # Other parameters.
  :developer_token: oaV6qLp9zQtGpCOfyOduag
  :client_customer_id: 760-711-7365
  :user_agent: quotensure-report
  :oauth2_token:
    :access_token: ya29.dgFnBEBM8DmYlwUpFOqZz3IM91xFRFwUhvhTTFpWz_WB3dstODF3psCJxHAET1s7COA0x2RP02y5fw
    :refresh_token: 1/bJkY9P1MYuQ5weMA_5VSHs738diu6gowr8QQBFpAsS4
    :issued_at: 2015-05-16 20:14:13.852814476 -04:00
    :expires_in: 3600
    :id_token: 
:service:
  :environment: PRODUCTION
:connection:
  :enable_gzip: false
:library:
  :log_level: INFO
  # Optional: uncomment to skip header / summary rows in reporting.
  # :skip_report_header: true
  # :skip_report_summary: false
  # :skip_column_header: true
